# This is a sample build configuration for PHP.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment
image: bodva/sqlunit:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - composer --version
          - cp .env.example .env
          - composer install
          - vendor/bin/phpunit --version
          - mysql --version
          - service mysql start
          - php artisan migrate
          - phpunit