image: clockwise/php7-mysql-unit-docker

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - composer --version
          # install composer vendor scripts
          - composer install
          - vendor/bin/phpunit --version
          - mysql --version
          # start mysl
          - service mysql start
          # create default databese for project
          - mysql -u root -e "CREATE DATABASE $DB_DATABASE"
          # migrate
          - php artisan migrate --seed
          # run tests
          - vendor/bin/phpunit